app.base.url=https://practicesoftwaretesting.com/
browser=chrome
user.login.email=customer2@practicesoftwaretesting.com
user.login.password=welcome01
user.login.wrong.password=WrongPass@123
user.change.current.password=welcome01
user.change.new.password=welcome02
user.change.confirm.password=welcome02

user.update.profile.first.name="FirstTest"
user.update.profile.last.name="Last"
user.update.profile.phone.number="254784415"
user.reset.email=Tester@yopmail.com
user.reset.registered.email=customer2@practicesoftwaretesting.com

api.base.url=https://api.practicesoftwaretesting.com
api.user.email=customer2@practicesoftwaretesting.com
api.user.password=welcome01

implicitWait=10
explicitWait=15