app.base.url=https://practicesoftwaretesting.com/
browser=chrome
user.login.email=customer3@practicesoftwaretesting.com
user.login.password=welcome01
user.login.wrong.password=WrongPass@123
user.change.current.password=welcome01@Passs1
user.change.new.password=welcome01@Passs2
user.change.confirm.password=welcome01@Passs2
user.reset.email=Tester4@yopmail.com
user.reset.registered.email=customer3@practicesoftwaretesting.com
implicitWait=10
explicitWait=15