api.base.url=https://api.practicesoftwaretesting.com
api.user.email=customer2@practicesoftwaretesting.com
api.user.password=welcome01

api.user.reset.email=customer@practicesoftwaretesting.com
api.user.wrong.password=Wellness@123