api.base.url=https://api.practicesoftwaretesting.com
api.user.email=apitester_1775253456636@yopmail.com
api.user.password=Toolshopuser@1

api.user.reset.email=customer@practicesoftwaretesting.com
api.user.wrong.password=Wellness@123