app.base.url=https://practicesoftwaretesting.com/
browser=edge
user.login.email=customer2@practicesoftwaretesting.com
user.login.password=welcome01
user.login.wrong.password=welcomeWrong01@Pass
user.change.current.password=welcome01@Pass
user.change.new.password=welcome01@Pass1
user.change.confirm.password=welcome01@Pass1
user.reset.email=Tester4@yopmail.com
user.reset.registered.email=customer2@practicesoftwaretesting.com
implicitWait=10
explicitWait=15